apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: okd-coreos-all
spec:
  params:
    - default: "https://github.com/openshift/os.git"
      name: repo
      type: string
    - default: "release-4.12"
      name: branch
      type: string
    - default: "scos"
      name: variant
      type: string
    - default: "4.12"
      name: version
      type: string
    - default: "registry.ci.openshift.org/origin/4.12:artifacts"
      name: rpm-artifacts-image
      type: string
    - name: target-registry
      default: "quay.io/okd"
      type: string
    - name: baseos-container-image-name
      default: "centos-stream-coreos-9"
      type: string
    - name: baseos-container-image-tag
      default: devel
      type: string
    - name: extensions-container-image-name
      default: "centos-stream-coreos-9-extensions"
      type: string
    - name: extensions-container-image-tag
      default: devel
      type: string
  tasks:
    - name: rpm-artifacts-copy
      params:
        - name: image
          value: $(params.rpm-artifacts-image)
      taskRef:
        kind: Task
        name: rpm-artifacts-copy
      workspaces:
        - name: ws
          workspace: shared-workspace
    - name: cosa-init
      params:
        - name: repo
          value: $(params.repo)
        - name: branch
          value: $(params.branch)
        - name: variant
          value: $(params.variant)
        - name: version
          value: $(params.version)
      runAfter:
        - rpm-artifacts-copy
      taskRef:
        kind: Task
        name: cosa-init
      workspaces:
        - name: ws
          workspace: shared-workspace
    - name: cosa-build
      runAfter:
        - cosa-init
      taskRef:
        kind: Task
        name: cosa-build
      workspaces:
        - name: ws
          workspace: shared-workspace
    - name: cosa-test
      runAfter:
        - cosa-build
      taskRef:
        kind: Task
        name: cosa-test
      workspaces:
        - name: ws
          workspace: shared-workspace
    - name: cosa-upload-images
      runAfter:
        - cosa-test
      taskRef:
        kind: Task
        name: cosa-upload-images
      params:
        - name: target-registry
          value: $(params.target-registry)
        - name: baseos-container-image-name
          value: $(params.baseos-container-image-name)
        - name: baseos-container-image-tag
          value: $(params.baseos-container-image-tag)
        - name: extensions-container-image-name
          value: $(params.extensions-container-image-name)
        - name: extensions-container-image-tag
          value: $(params.extensions-container-image-tag)
      workspaces:
        - name: ws
          workspace: shared-workspace
    - name: cosa-buildextend
      runAfter:
        - cosa-upload-images
      taskRef:
        kind: Task
        name: cosa-buildextend
      workspaces:
        - name: ws
          workspace: shared-workspace
  workspaces:
    - name: shared-workspace
