apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: okd-coreos-all
spec:
  params:
    - name: environment
      default: local
      type: string
    - default: "https://github.com/openshift/os.git"
      name: repo
      type: string
    - default: "release-4.12"
      name: branch
      type: string
    - default: "scos"
      name: variant
      type: string
    - default: "4.12"
      name: version
      type: string
    - default: "registry.ci.openshift.org/origin/4.12:artifacts"
      name: rpm-artifacts-image
      type: string
    - name: target-registry
      default: "quay.io/okd"
      type: string
    - name: baseos-container-image-name
      default: "centos-stream-coreos-9"
      type: string
    - name: extensions-container-image-name
      default: "centos-stream-coreos-9-extensions"
      type: string
    - name: tag-latest
      default: "false"
      type: string
    - name: s3-bucket-name
      default: ""
      type: string
    - name: s3-endpoint-url
      default: ""
      type: string
    - name: s3-aws-config-file
      default: "credentials"
      type: string
    # - name: matrix-room
    #   description: room id (in the format !<ROOM_ID>:<SERVER_NAME>)
    #   type: string
    #   default: "a_room"
    # - name: matrix-endpoint
    #   description: room id (in the format !<ROOM_ID>:<SERVER_NAME>)
    #   type: string
    #   default: "an_endpoint"
  tasks:
    - name: rpm-artifacts-copy
      params:
        - name: image
          value: $(params.rpm-artifacts-image)
      taskRef:
        kind: Task
        name: rpm-artifacts-copy
      workspaces:
        - name: ws
          workspace: shared-workspace
    - name: cosa-init
      params:
        - name: repo
          value: $(params.repo)
        - name: branch
          value: $(params.branch)
        - name: variant
          value: $(params.variant)
        - name: version
          value: $(params.version)
      runAfter:
        - rpm-artifacts-copy
      taskRef:
        kind: Task
        name: cosa-init
      workspaces:
        - name: ws
          workspace: shared-workspace
    - name: cosa-build-baseos
      runAfter:
        - cosa-init
      taskRef:
        kind: Task
        name: cosa-build-baseos
      params:
        - name: bucket-name
          value: $(params.s3-bucket-name)
        - name: endpoint-url
          value: $(params.s3-endpoint-url)
        - name: aws-config-file
          value: $(params.s3-aws-config-file)
      workspaces:
        - name: s3creds
          workspace: s3-credentials
        - name: ws
          workspace: shared-workspace
    - name: cosa-test
      params:
        - name: variant
          value: $(params.variant)
      runAfter:
        - cosa-build-baseos
      taskRef:
        kind: Task
        name: cosa-test
      workspaces:
        - name: ws
          workspace: shared-workspace
    - name: cosa-build-extensions
      runAfter:
        - cosa-test
      params:
        - name: variant
          value: $(params.variant)
      taskRef:
        kind: Task
        name: cosa-build-extensions
      workspaces:
        - name: ws
          workspace: shared-workspace
    - name: cosa-buildextend
      runAfter:
        - cosa-test
      taskRef:
        kind: Task
        name: cosa-buildextend
      workspaces:
        - name: ws
          workspace: shared-workspace
    - name: cosa-upload-baseos
      taskRef:
        kind: Task
        name: cosa-push-container
      runAfter:
        - cosa-buildextend
        - cosa-build-extensions
      params:
        - name: target-registry
          value: $(params.target-registry)
        - name: container-image-name
          value: $(params.baseos-container-image-name)
        - name: image
          value: ostree
        - name: tag
          value: $(params.version)
        - name: tag-latest
          value: $(params.tag-latest)
      workspaces:
        - name: regcred
          workspace: registry-credentials
        - name: ws
          workspace: shared-workspace
      when:
      - input: $(params.environment)
        operator: in
        values:
        - "operate-first"
      - input: $(tasks.cosa-buildextend.results.output)
        operator: in
        values: ["OK"] # Using $(tasks.cosa-buildextend.status) did not pass validation webhook
      - input: $(tasks.cosa-build-extensions.results.output)
        operator: in
        values: ["OK"]

    - name: cosa-upload-extensions
      taskRef:
        kind: Task
        name: cosa-push-container
      runAfter:
        - cosa-buildextend
        - cosa-build-extensions
      when:
      - input: $(params.environment)
        operator: in
        values:
        - "operate-first"
      - input: $(tasks.cosa-buildextend.results.output)
        operator: in
        values: ["OK"] # Using $(tasks.cosa-buildextend.status) did not pass validation webhook
      - input: $(tasks.cosa-build-extensions.results.output)
        operator: in
        values: ["OK"]
      params:
        - name: target-registry
          value: $(params.target-registry)
        - name: container-image-name
          value: $(params.extensions-container-image-name)
        - name: image
          value: extensions-container
        - name: tag
          value: $(params.version)
        - name: tag-latest
          value: $(params.tag-latest)
      workspaces:
        - name: regcred
          workspace: registry-credentials
        - name: ws
          workspace: shared-workspace
    - name: cosa-upload-bootimages
      taskRef:
        kind: Task
        name: cosa-upload-s3
      runAfter:
        - cosa-buildextend
        - cosa-build-extensions
      when:
      - input: $(params.environment)
        operator: in
        values:
        - "operate-first"
      - input: $(tasks.cosa-buildextend.results.output)
        operator: in
        values: ["OK"] # Using $(tasks.cosa-buildextend.status) did not pass validation webhook
      - input: $(tasks.cosa-build-extensions.results.output)
        operator: in
        values: ["OK"]
      params:
        - name: bucket-name
          value: $(params.s3-bucket-name)
        - name: endpoint-url
          value: $(params.s3-endpoint-url)
        - name: aws-config-file
          value: $(params.s3-aws-config-file)
      workspaces:
        - name: s3creds
          workspace: s3-credentials
        - name: ws
          workspace: shared-workspace        
  # finally:
  #   - name: notify-matrix
  #     when: 
  #       - input: "${params.environment}"
  #         operator: in
  #         values: ["operate-first"]
  #     params:
  #       - name: matrix-access-token
  #         value: matrix-access-token
  #       - name: endpoint
  #         value: $(params.matrix-endpoint)
  #       - name: room
  #         value: $(params.matrix-room)
  #       - name: message
  #         value: "PipelineRun $(context.pipelineRun.name) - $(params.variant) - version $(params.version): Build from branch $(params.branch) $(tasks.status)"
  #     taskRef:
  #       kind: Task
  #       name: notify-matrix
  workspaces:
    - name: registry-credentials
    - name: s3-credentials
    - name: shared-workspace
