apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cosa-upload-images
spec:
  params:
    - name: target-registry
      default: "quay.io/okd"
      type: string
    - name: baseos-container-image-name
      default: "centos-stream-coreos-9"
      type: string
    - name: baseos-container-image-tag
      default: devel
      type: string
    - name: extensions-container-image-name
      default: "centos-stream-coreos-9-extensions"
      type: string
    - name: extensions-container-image-tag
      default: devel
      type: string
  steps:
    - image: 'quay.io/coreos-assembler/coreos-assembler:latest'
      name: upload-images
      resources:
        limits:
          devices.kubevirt.io/kvm: '1'
          memory: 4Gi
        requests:
          devices.kubevirt.io/kvm: '1'
          memory: 4Gi
      script: |
        #!/usr/bin/env bash
        set -euxo pipefail

        cd /workspace/coreos
        cosa push-container $(params.target-registry)/$(params.baseos-container-image-name):$(params.baseos-container-image-tag)
        cosa push-container --image=extensions-container $(params.target-registry)/$(params.extensions-container-image-name):$(params.extensions-container-image-tag)

  workspaces:
    - mountPath: /workspace
      name: ws
