apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cosa-build
spec:
  steps:
    - image: 'quay.io/coreos-assembler/coreos-assembler:latest'
      name: fetch-and-build
      resources:
        limits:
          devices.kubevirt.io/kvm: '1'
          memory: 4Gi
        requests:
          devices.kubevirt.io/kvm: '1'
          memory: 4Gi
      script: |
        #!/usr/bin/env bash
        set -euxo pipefail

        cd /workspace/coreos
        cosa fetch
        cosa build ostree
        
        # The rpms that were extracted from the artifacts image
        # are not present inside the container used to build the
        # extensions, however `rpm-ostree compose extensions`
        # will try to fetch metadata for all repos listed in
        # {manifest,extensions}.yaml 
        # TODO: Find a more elegant way to do this
        sed -i 's/- artifacts//' "src/config/manifest.yaml"
        cosa build-extensions-container

  workspaces:
    - mountPath: /workspace
      name: ws
