apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cosa-buildextend
spec:
  steps:
    - image: 'quay.io/coreos-assembler/coreos-assembler:latest'
      name: buildextend
      resources:
        limits:
          devices.kubevirt.io/kvm: '1'
          cpu: 1000m
          memory: 4Gi
        requests:
          devices.kubevirt.io/kvm: '1'
          cpu: 1000m
          memory: 4Gi
      script: |
        #!/usr/bin/env bash
        set -euxo pipefail

        cd /workspace/coreos
        cosa buildextend-metal4k
        cosa buildextend-metal
        cosa buildextend-live

  workspaces:
    - mountPath: /workspace
      name: ws
