apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cosa-test
spec:
  steps:
    - image: 'quay.io/coreos-assembler/coreos-assembler:latest'
      name: build-and-test-qemu
      resources:
        limits:
          devices.kubevirt.io/kvm: '1'
          memory: 4Gi
        requests:
          devices.kubevirt.io/kvm: '1'
          memory: 4Gi
      script: |
        #!/usr/bin/env bash
        set -euxo pipefail

        cd /workspace/coreos
        cosa buildextend-qemu
        cosa kola --basic-qemu-scenarios

  workspaces:
    - mountPath: /workspace
      name: ws
