apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cosa-build-baseos
spec:
  steps:
    - image: 'quay.io/coreos-assembler/coreos-assembler:latest'
      name: fetch-and-build-baseos
      resources:
        limits:
          devices.kubevirt.io/kvm: '1'
          cpu: 1000m
          memory: 4Gi
        requests:
          devices.kubevirt.io/kvm: '1'
          cpu: 1000m
          memory: 4Gi
      script: |
        #!/usr/bin/env bash
        set -euxo pipefail

        cd /workspace/coreos

        cosa fetch
        cosa build ostree

  workspaces:
    - mountPath: /workspace
      name: ws
