apiVersion: v1
kind: Secret
metadata:
  name: okd-okd-robot-pull-secret
  namespace: okd-coreos-pipeline
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJxdWF5LmlvIjogewogICAgICAiYXV0aCI6ICJiMnRrSzI5clpGOXliMkp2ZERvM05qZzFRalU1UmxGVFJUZzFRMFpHTmt4Q05FRTNPVGswVmtaTFVrODRWRWN5V1ZKSE1VODFVVVpOVjAwNFFVdzRNamhHVERreVJWZFhTemsyVFV0UiIsCiAgICAgICJlbWFpbCI6ICIiCiAgICB9CiAgfQp9
type: kubernetes.io/dockerconfigjson