apiVersion: batch/v1
kind: CronJob
metadata:
  name: okd-coreos-4.16-prod-create-daily
spec:
  schedule: "30 10 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
          - name: workspace
            emptyDir: {}
          containers:
          - name: send-trigger
            image: curlimages/curl
            command:
              - /bin/sh
            args:
              - -ce
              - |
                cat <<EOF > /workspace/post-body.json
                {
                  "params": {
                    "branch": "${BRANCH}",
                    "version": "${OKD_VERSION}",
                    "release-stream": "${RELEASE_STREAM}",
                    "tag-latest": "${TAG_LATEST}",
                    "claimname": "${CLAIMNAME}",
                    "variant": "${VARIANT}"
                  }
                }
                EOF
                curl -d @/workspace/post-body.json $SINK_URL
            volumeMounts:
            - mountPath: /workspace
              name: workspace
            env:
              - name: SINK_URL
                value: "http://el-okd-coreos-prod.okd-coreos.svc.cluster.local:8080"
              - name: BRANCH
                value: "release-4.16"
              - name: OKD_VERSION
                value: "4.16"
              - name: RELEASE_STREAM
                value: "stable"
              - name: TAG_LATEST
                value: "true"
              - name: CLAIMNAME
                value: "pipeline-scos-4.16-pvc"
              - name: VARIANT
                value: "c9s"
            resources:
              limits:
                cpu: 100m
                memory: 128Mi
          restartPolicy: Never
          dnsPolicy: ClusterFirst
