apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: okd-coreos-4.19-dev-pipelinerun-
  annotations:
    operator.tekton.dev/prune.skip: "false"
    operator.tekton.dev/prune.resources: "taskrun, pipelinerun"
    operator.tekton.dev/prune.keep: "1"
    operator.tekton.dev/prune.strategy: "keep"
spec:
  params:
    - name: repo
      value: "https://github.com/openshift/os.git"
    - name: branch
      value: "master"
    - name: variant
      value: "okd-c9s"
    - name: version
      value: "4.19"
    - name: release-stream
      value: "next"
    - name: target-registry
      value: "quay.io/okd"
    - name: baseos-container-image-name
      value: "centos-stream-coreos-9"
    - name: extensions-container-image-name
      value: "centos-stream-coreos-9-extensions"
    - name: s3-bucket-name
      value: "okd-scos"
    - name: s3-endpoint-url
      value: "https://okd-scos.s3.amazonaws.com/"
    - name: matrix-room
      value: ""
    - name: matrix-endpoint
      value: ""
    - name: upload-container-images
      value: "false"
    - name: tag-latest
      value: "false"
    - name: upload-bootimages
      value: "false"
    - name: notify-matrix
      value: "false"
  pipelineRef:
    name: okd-coreos
  timeouts:
    pipeline: "4h0m0s"
  workspaces:
    - name: registry-credentials
      secret:
        secretName: my-secret
    - name: s3-credentials
      emptyDir: {}
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 40Gi
