apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cosa-test
spec:
  params:
    - name: variant
      default: "scos"
      type: string
  steps:
    - image: 'quay.io/coreos-assembler/coreos-assembler:latest'
      name: build-and-test-qemu
      resources:
        limits:
          cpu: 1000m
          devices.kubevirt.io/kvm: '1'
          memory: 4Gi
        requests:
          cpu: 1000m
          devices.kubevirt.io/kvm: '1'
          memory: 4Gi
      script: |
        #!/usr/bin/env bash
        set -euxo pipefail

        cd /srv/coreos
        cosa buildextend-qemu
        if [[ "$(params.variant)" != "scos" ]]; then
          cosa kola --basic-qemu-scenarios
        else
          cosa kola --basic-qemu-scenarios --skip-secure-boot
        fi
  workspaces:
    - mountPath: /srv
      name: ws
