apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cosa-buildextend
spec:
  steps:
    - image: 'quay.io/coreos-assembler/coreos-assembler:latest'
      name: buildextend
      resources:
        limits:
          cpu: 1000m
          devices.kubevirt.io/kvm: '1'
          memory: 4Gi
        requests:
          cpu: 1000m
          devices.kubevirt.io/kvm: '1'
          memory: 4Gi
      script: |
        #!/usr/bin/env bash
        set -euxo pipefail

        cd /srv/coreos
        cosa buildextend-metal4k
        cosa buildextend-metal
        cosa buildextend-live
        cosa buildextend-openstack
        printf "%s" "OK" > $(results.output.path)

  results:
    - name: output
  workspaces:
    - mountPath: /srv
      name: ws
