apiVersion: batch/v1
kind: CronJob
metadata:
  name: daily-job
spec:
  schedule: "0 6 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: daily-job
            image: curlimages/curl
            resources:
              limits:
                cpu: 100m
                memory: 128Mi
          restartPolicy: Never
